### ISSUE TITLE
Error-First Callback

### ISSUE THREAD

**Issue by noamokman** [mertkahyaoglu/node-movie#1]
Hi there!
I think you should follow on the standard of node callbacks [Error-First Callback](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/)

If you want, I'll PR to change the api.

BTW, I think you should read the [Semantic Versioning 2.0.0](http://semver.org/) website,
you recently (8 hours ago) updated to 1.3.0 with a breaking change, that should have been a major release. (so will changing the callback pattern)

thanks,
Love the package!

**Comment by mertkahyaoglu** [comment]
Thank you :+1: I appreciate it and feel free to PR please.

**Comment by mertkahyaoglu** [comment]
I think it's ok now. 08bade3897acdb2d78966c3258a6876a4f77acf6

**Comment by noamokman** [comment]
Great work! :+1:
